document:
  type: Linee guida
  name: Regole Tecniche e Raccomandazioni afferenti la generazione di certificati elettronici qualificati, firme e sigilli elettronici qualificati e validazioni temporali elettroniche qualificate
  short_name: Ll.gg. certificati qualificati
  author: walter-arrighetti
  contributors:
    - Stefano Arbia
    - Walter Arrighetti
    - Antonio Florio
    - Stefano Ianniello
    - Andrea Spallacci
  description: |
    Regole Tecniche e Raccomandazioni afferenti la generazione di certificati elettronici qualificati, firme e sigilli elettronici qualificati e validazioni temporali elettroniche qualificate
  tags:
    - eIDAS
    - QSignature
    - QSeal
    - QWAC
    - time stamping
    - qualified trust service
    - firma elettronica qualificata
    - sigillo elettronico qualificato
    - certificato elettronico qualificato
  origin: https://github.com/test-lg/NAME-OF-REPOSITORY/
